Simple example of implementation Genetic Algorithm for Travelling Salesman Problem

Penerapan Algoritma Genetik untuk menyelesaikan TSP

import library

memanggil library

In [0]:
import numpy as np 
import operator
import pandas as pd
import matplotlib.pyplot as plt
import random
from array import *

Create city list. The are given 5 cities

Membuat daftar kota dalam bentuk array

In [0]:
daftarKota = [[0, 0], [5, 6], [1, 4], [3,4],[7,7]]
for i in daftarKota:
    for j in i:
        print(j,end = " ")
    print()

jumlahKota =  len(daftarKota)   

0 0 
5 6 
1 4 
3 4 
7 7 


Inisialisasi Populasi secara acak

Array P diinisialisasi sebagai array integer

Solusi awal dibuat dengan random permutation

In [0]:
def initPopulasi(ukuranPopulasi,jumlahKota):
  P = np.empty((ukuranPopulasi,jumlahKota))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahKota)
    for j in range(jumlahKota):
      P[i][j]=I[j]
  return P


#ukuranPopulasi = 4
#P = initPopulasi (ukuranPopulasi,jumlahKota)
#print(P)
#print(P.dtype)


Membuat fungsi objektif

Jarak yang diukur adalah jarak euclidian

In [0]:
def fungsiObjectif(populasi,daftarKota):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak  = matrikJarak.astype('float')
  n = len(daftarKota)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = daftarKota[populasi[i][j]][0]-daftarKota[populasi[i][j+1]][0]
      jrkY = daftarKota[populasi[i][j]][1]-daftarKota[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((daftarKota[populasi[i][n-1]][0]-daftarKota[populasi[i][0]][0])**2+ (daftarKota[populasi[i][n-1]][1]-daftarKota[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

#fitP = fungsiObjectif(P,daftarKota)
#print(fitP)
#print(fitP.dtype)



Seleksi menggunakan metode tournamen wheel

Ukuran turname k = 2

Jumlah induk yang dipilih adalah 2

In [0]:

def seleksi (P):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  Induk = np.empty((jmlInduk,jumlahKota))
  Induk = Induk.astype('int')
  
  for i in range (2):
    # memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    #print("i :",i)
    #print(":r1 :",r1, "fsObj[r1] ",fsObj[r1])
    #print(":r2 :",r2, "fsObj[r2] ",fsObj[r2])

    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahKota):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahKota):
        Induk [i][j] = P[r2][j]
  return Induk

#Induk = seleksi(P)
#print(Induk)

Rekombinasi menggunaka metode Partially Mixed Crossover (PMX)
Jumlah anak yang dihasilkan adalah 2

In [0]:
#crossover 

def PMX(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]
  #print(sz, brs, kol)

  I1 = np.empty((kol))
  I2 = np.empty((kol))
  A1 = np.empty((kol))
  A2 = np.empty((kol))
  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')


  for i in range(kol):    
    I1[i]= Induk[0][i]
    I2[i]= Induk[1][i]

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 
    A1[i0] = I1[i0]
    A2[i0]= I2[i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = I1[m]
    n2 = I2[m]

    #mengecek apakah kota tertentu sudah ada di anak
    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>kol:
        idxAda1 = 1

      if A1[j1] == n2:
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>kol:
        idxAda2 = 1

      if A2[j2] == n1:
        idxAda2 = 1
      
    if idxAda1 == 0:
      A1[batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      A2[batasCek2] = n1 
      batasCek2 = batasCek2 +1
    
  for i in range (kol):
    Anak[0][i]= A1[i]
    Anak[1][i]= A2[i]
   
  return Anak

#AnakCX = PMX(Induk)
#print("Anak :",AnakCX)





Mutasi dengan Swap

index kota yang di swap pada kedua anak sama

In [0]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  #print("Induk :",Induk)

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)

  if r1 < r2:
    rs1 = r1
    rs2 = r2
  else:
    rs1 = r2
    rs2 = r1

  I1rs1 = Induk [0][rs1]
  I1rs2 = Induk [0][rs2]
  I2rs1 = Induk [1][rs1]
  I2rs2 = Induk [1][rs2] 

  Anak [0][rs1] = I1rs2 
  Anak [0][rs2] = I1rs1
  Anak [1][rs1] = I2rs2  
  Anak [1][rs2] = I2rs1

  return Anak

#print("AnakCX :",AnakCX)
#AnakM = MutasiSwap(AnakCX)
#print("AnakM :",AnakM)


Elitism (steady state replacement)

In [0]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)
  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]

  return [P,fitP]


#print(P)
#print(Anak)
#print(fitP)
#print(fitAnak)
#P = Elitism (P,Anak,fitP,fitAnak)
#print(P)
#print(fitP)


Prosedur GA 

In [0]:
# Inisialisasi paramater
PCX = 0.95
Pm = 0.01
ukuranPopulasi = 4
max_generasi = 5

# Inisialisasi populasi 

P = initPopulasi (ukuranPopulasi,jumlahKota)
print("P0 :",P)

#melakukan evaluasi P
fitP = fungsiObjectif(P,daftarKota)
print("fitness populasi awal:",fitP)

print("fitness terbaik awal:",fitP.min())
print("rute awal :",P[fitP.argmin()])


for i in range(max_generasi):
  Induk = seleksi(P)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)

  fitAnak = fungsiObjectif(Anak,daftarKota)
  #print("fitAnak :",fitAnak)

  [P, fitP]= Elitism (P,Anak,fitP,fitAnak)   
  
print("fitness populasi akhir:",fitP)
print("fitness akhir:",fitP.min())
print("rute akhir :",P[fitP.argmin()])




P0 : [[1 4 3 2 0]
 [0 4 2 1 3]
 [3 4 2 0 1]
 [1 4 3 2 0]]
fitness populasi awal: [21.16942328 28.90826195 26.46998636 21.16942328]
fitness terbaik awal: 21.169423279024105
rute awal : [1 4 3 2 0]
fitness populasi akhir: [20.89580466 20.83130956 20.89580466 20.89580466]
fitness akhir: 20.83130955811703
rute akhir : [1 4 3 0 2]
